### ISSUE TITLE
How to handle with the missing value in the genotype

### ISSUE THREAD

**Issue by Spatial-R** [snaketron/genphen#2]
Hello, I'm so sorry to bother you again. When using the genphen package to analysis the associations between genotype and phenotype, how can I to handle with the missing value in genotype. Fox example, there are some missing positions in the genotype, which were filled with the symptom "-".  Are there any specificed  settings in the **runGenphen** function? 
Best!

**Comment by snaketron** [comment]
Hi @Spatial-R ,

genphen does not do imputation of missing genotypes. Thus, if you call runGenphen, the gaps will be considered as just another genotype category. 

Perhaps you should use an additional method for the genotype imputation before using genphen.

Best
